---
name: Code Coverage
on: [push]
jobs:
  job_grcov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: get toolchain nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: cargo build with special profiling
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
      - name: grcov run
        uses: actions-rs/grcov@v0.1
        config: configs/grcov.yml
      #- name: Coveralls upload
      #  uses: coverallsapp/github-action@master
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
      #    path-to-lcov: ${{ steps.coverage.outputs.report }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
            token: ${{ secrets.YOUR_SECRET_TOKEN }}
