# github workflows action file for si_trace_print
---
name: Rust
on:
  push:
  pull_request:
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
jobs:
  # MSRV check
  job_msrv:
    name: build MSRV ${{ matrix.msrv }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # `msrv` should match Cargo.toml:[package]:rust-version
        msrv: [1.53.0, 1.56.1, 1.58.1, 1.62.1, 1.66.1]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.msrv }}
      - name: Build using rust ${{ matrix.msrv }} on ${{ matrix.os }}
        shell: bash
        run: |
          set -eux
          cargo --version
          cargo build --lib --verbose
          cargo test --lib
  # do all the basic rust stuff
  job_fmt_clippy_build_buildrelease_test_doc:
    name: fmt clippy build test doc
    needs: [job_msrv]
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: Check rustfmt
        run: cargo fmt --verbose --check
      - name: Check clippy
        run: cargo clippy --no-deps --verbose --all-targets --all-features --
             -D warnings
      - name: Build Debug and Release
        run: |
          set -eux
          cargo build --verbose
          cargo build --verbose --release
      - name: Run All Tests Single-threaded
        run: |
          set -eux
          cargo test -j1 --verbose \
              --all-features \
              --future-incompat-report \
              -- \
              --test-threads=1
      - name: Run Lib Tests Multi-threaded
        run: |
          set -eux
          cargo test -j2 --lib --verbose -- --test-threads=2
          cargo test -j4 --lib --verbose -- --test-threads=4
          cargo test -j8 --lib --verbose -- --test-threads=8
          cargo test -j8 --lib --verbose -- --test-threads=16
      - name: Build Documentation
        run: cargo doc --locked --release --frozen --no-deps -v
  # run code coverage with rust "nightly", upload to codecov.io
  # help from
  # - https://github.com/marketplace/actions/rust-grcov
  # - https://eipi.xyz/blog/rust-code-coverage-with-github-workflows/
  # - https://github.com/mozilla/grcov#lcov-output
  job_grcov:
    name: grcov
    runs-on: ubuntu-latest
    needs: [job_msrv, job_fmt_clippy_build_buildrelease_test_doc]
    steps:
      - name: git checkout
        uses: actions/checkout@v1
      - name: get toolchain nightly
        uses: actions-rs/toolchain@v1
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: -Zprofile
                     -Ccodegen-units=1 -Cinline-threshold=0
                     -Clink-dead-code -Coverflow-checks=off
                     -Cpanic=abort -Zpanic_abort_tests
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: cargo install
        uses: actions-rs/cargo@v1
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: -Zprofile
                     -Ccodegen-units=1 -Cinline-threshold=0
                     -Clink-dead-code -Coverflow-checks=off
                     -Cpanic=abort -Zpanic_abort_tests
        with:
          command: install
          args: --verbose -- rustfilt grcov
      - name: cargo build with special profiling
        uses: actions-rs/cargo@v1
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: -Zprofile
                     -Ccodegen-units=1 -Cinline-threshold=0
                     -Clink-dead-code -Coverflow-checks=off
                     -Cpanic=abort -Zpanic_abort_tests
        with:
          command: build
          args: --verbose
      - name: cargo test with special profiling
        uses: actions-rs/cargo@v1
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: -Zprofile
                     -Ccodegen-units=1 -Cinline-threshold=0
                     -Clink-dead-code -Coverflow-checks=off
                     -Cpanic=abort -Zpanic_abort_tests
        with:
          command: test
          args: --lib --no-fail-fast
      - name: grcov
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: -Zprofile
                     -Ccodegen-units=1 -Cinline-threshold=0
                     -Clink-dead-code -Coverflow-checks=off
                     -Cpanic=abort -Zpanic_abort_tests
        run: |
          set -eux
          grcov \
              . \
              --source-dir ./src \
              --log-level DEBUG \
              --llvm \
              --binary-path ./target/debug/ \
              --branch \
              --ignore-not-existing \
              --output-type lcov \
              --output-path lcov.info
          ls -l
          head lcov.info
      # action from https://github.com/codecov/codecov-action
      - name: upload codecov
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          verbose: true
          fail_ci_if_error: true
          # public repository does not need secret section `with: token`
          # see
          # https://about.codecov.io/blog/javascript-code-coverage-using-github-actions-and-codecov/
          #
          # list of acceptable formats
          # https://docs.codecov.com/docs/supported-report-formats
